"""empty message

Revision ID: 08859847cd65
Revises: a6c639d69bbe
Create Date: 2019-09-22 01:36:13.338258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08859847cd65'
down_revision = 'a6c639d69bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_purchase_order', sa.Column('amount', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_purchase_order', 'amount')
    # ### end Alembic commands ###
