"""empty message

Revision ID: 178187c64250
Revises: dbdaea4787b7
Create Date: 2019-06-28 01:36:28.034971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178187c64250'
down_revision = 'dbdaea4787b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['make.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('vehicle_model', sa.Column('make_id', sa.Integer(), nullable=True))
    op.add_column('vehicle_model', sa.Column('year', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vehicle_model', 'make', ['make_id'], ['id'])
    op.drop_column('vehicle_model', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_model', sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vehicle_model', type_='foreignkey')
    op.drop_column('vehicle_model', 'year')
    op.drop_column('vehicle_model', 'make_id')
    op.drop_table('model')
    # ### end Alembic commands ###
