"""empty message

Revision ID: 249f722b04c6
Revises: 
Create Date: 2019-07-20 18:09:28.560217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249f722b04c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.uuid'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('lpo_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('part_id', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.uuid'], ),
    sa.ForeignKeyConstraint(['order_id'], ['local_purchase_order.uuid'], ),
    sa.ForeignKeyConstraint(['part_id'], ['part.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_index('entries_credit_idx', table_name='entries')
    op.drop_index('entries_debit_idx', table_name='entries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('entries_debit_idx', 'entries', ['debit'], unique=False)
    op.create_index('entries_credit_idx', 'entries', ['credit'], unique=False)
    op.drop_table('lpo_item')
    op.drop_table('local_purchase_order')
    # ### end Alembic commands ###
