"""empty message

Revision ID: 2b6602fae009
Revises: 178187c64250
Create Date: 2019-06-29 15:06:53.259411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6602fae009'
down_revision = '178187c64250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part', sa.Column('make_id', sa.String(length=50), nullable=True))
    op.drop_column('part', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part', sa.Column('quantity', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('part', 'make_id')
    # ### end Alembic commands ###
