"""empty message

Revision ID: 4f82e184e833
Revises: af9b784fa92c
Create Date: 2019-08-19 02:49:15.682565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f82e184e833'
down_revision = 'af9b784fa92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('item', sa.String(length=80), nullable=True),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.String(length=50), nullable=True),
    sa.Column('narration', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_column('item_log', 'supplier_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_log', sa.Column('supplier_price', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_table('expense')
    # ### end Alembic commands ###
