"""empty message

Revision ID: 5713e475f0e0
Revises: 3a31067b3ec0
Create Date: 2019-06-25 19:43:18.995807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5713e475f0e0'
down_revision = '3a31067b3ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part', sa.Column('model_id', sa.String(length=50), nullable=True))
    op.add_column('part', sa.Column('type_id', sa.String(length=50), nullable=True))
    op.drop_column('part', 'model')
    op.drop_column('part', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('part', sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('part', 'type_id')
    op.drop_column('part', 'model_id')
    # ### end Alembic commands ###
