"""empty message

Revision ID: 6b99550370f1
Revises: 5713e475f0e0
Create Date: 2019-06-25 19:59:22.366395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b99550370f1'
down_revision = '5713e475f0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('part', sa.Column('category_id', sa.String(length=50), nullable=True))
    op.add_column('part', sa.Column('code', sa.String(length=200), nullable=False))
    op.create_foreign_key(None, 'part', 'part_category', ['category_id'], ['uuid'])
    op.drop_column('part', 'type_id')
    op.create_foreign_key(None, 'part_log', 'part', ['part_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'part_log', type_='foreignkey')
    op.add_column('part', sa.Column('type_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'part', type_='foreignkey')
    op.drop_column('part', 'code')
    op.drop_column('part', 'category_id')
    op.drop_table('part_category')
    # ### end Alembic commands ###
