"""empty message

Revision ID: 6d8077ac1e45
Revises: daedf8cedbc2
Create Date: 2019-07-21 02:02:38.871233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8077ac1e45'
down_revision = 'daedf8cedbc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('part_vendor_id_fkey', 'part', type_='foreignkey')
    op.drop_column('part', 'vendor_id')
    op.drop_column('part', 'vendor_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part', sa.Column('vendor_price', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('part', sa.Column('vendor_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key('part_vendor_id_fkey', 'part', 'vendor', ['vendor_id'], ['uuid'])
    # ### end Alembic commands ###
