"""empty message

Revision ID: 9e73f8ff23c9
Revises: 89467ad7cffb
Create Date: 2019-09-18 20:34:52.813560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e73f8ff23c9'
down_revision = '89467ad7cffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_log', sa.Column('credit_status', sa.String(length=50), nullable=True))
    op.add_column('item_log', sa.Column('on_credit', sa.Boolean(), nullable=True))
    op.add_column('item_log', sa.Column('pay_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_log', 'pay_type')
    op.drop_column('item_log', 'on_credit')
    op.drop_column('item_log', 'credit_status')
    # ### end Alembic commands ###
