"""empty message

Revision ID: a6c639d69bbe
Revises: e46fedf988e9
Create Date: 2019-09-22 01:25:45.776997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c639d69bbe'
down_revision = 'e46fedf988e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenditure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('pay_type', sa.String(length=50), nullable=True),
    sa.Column('on_credit', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('credit_status', sa.String(length=50), nullable=True),
    sa.Column('narration', sa.String(length=4000), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.uuid'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('local_purchase_order', sa.Column('credit_status', sa.String(length=50), nullable=True))
    op.add_column('local_purchase_order', sa.Column('on_credit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_purchase_order', 'on_credit')
    op.drop_column('local_purchase_order', 'credit_status')
    op.drop_table('expenditure')
    # ### end Alembic commands ###
