"""empty message

Revision ID: af9b784fa92c
Revises: 
Create Date: 2019-08-14 11:44:48.914317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9b784fa92c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('entries_credit_idx', table_name='entries')
    op.drop_index('entries_debit_idx', table_name='entries')
    op.add_column('item_log', sa.Column('supplier_price', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_log', 'supplier_price')
    op.create_index('entries_debit_idx', 'entries', ['debit'], unique=False)
    op.create_index('entries_credit_idx', 'entries', ['credit'], unique=False)
    # ### end Alembic commands ###
