"""empty message

Revision ID: c0c62dcff64a
Revises: 
Create Date: 2019-07-01 03:10:25.128400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c62dcff64a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('entries_credit_idx', table_name='entries')
    op.drop_index('entries_debit_idx', table_name='entries')
    op.create_foreign_key(None, 'job_item', 'part', ['item'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_item', type_='foreignkey')
    op.create_index('entries_debit_idx', 'entries', ['debit'], unique=False)
    op.create_index('entries_credit_idx', 'entries', ['credit'], unique=False)
    # ### end Alembic commands ###
