"""empty message

Revision ID: d16fb19f9cde
Revises: edb2e5ca8e57
Create Date: 2019-06-27 15:34:18.455406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16fb19f9cde'
down_revision = 'edb2e5ca8e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part', sa.Column('vendor_id', sa.String(length=50), nullable=True))
    op.add_column('part', sa.Column('vendor_price', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'part', 'vendor', ['vendor_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'part', type_='foreignkey')
    op.drop_column('part', 'vendor_price')
    op.drop_column('part', 'vendor_id')
    # ### end Alembic commands ###
