"""empty message

Revision ID: e46fedf988e9
Revises: 9e73f8ff23c9
Create Date: 2019-09-19 10:29:46.446480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46fedf988e9'
down_revision = '9e73f8ff23c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_purchase_order', sa.Column('narration', sa.String(length=50), nullable=True))
    op.add_column('local_purchase_order', sa.Column('pay_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_purchase_order', 'pay_type')
    op.drop_column('local_purchase_order', 'narration')
    # ### end Alembic commands ###
