"""empty message

Revision ID: e8d103bc4e3f
Revises: 61e148922e19
Create Date: 2019-09-16 11:34:34.156969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d103bc4e3f'
down_revision = '61e148922e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('entity_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'entity_id')
    # ### end Alembic commands ###
