DROP TABLE IF EXISTS entries CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS alembic_version;
DROP TABLE IF EXISTS item_log CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS item_balances CASCADE;

